### ISSUE TITLE
Summer Projects

### ISSUE THREAD

**Issue by murrown** [OSU-Net/cyder#689]
This is a short checklist of major tasks that we'd like to implement over the summer.

- [x] https://github.com/OSU-Net/cyder/issues/653 Add containers to DNS objects and make sure permissions work correctly
- [x] https://github.com/OSU-Net/cyder/issues/688 Update, don't delete objects when resolving domain name conflicts
- [ ] https://github.com/OSU-Net/cyder/issues/644 Upgrade to a version of Django that was released in the past year (shouldn't be too difficult)
- [ ] https://github.com/OSU-Net/cyder/issues/690 Get object changelogs working
- [ ] https://github.com/OSU-Net/cyder/pull/693 Create a custom attributes form for users
- [ ] More/better user preferences in general
